<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Welcome </title>

        <link href="/bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet">

        <style>
            .container {
                margin-top: 80px;
            }

            .bg-dark {
                background-color: #3b8dbd !important;
            }
        </style>
    </head>

    <body>

        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
            <a class="navbar-brand" href="/">Main</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarsExampleDefault"
                    aria-controls="navbarsExampleDefault" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </nav>

        <div class="modal-dialog text-center">
            <div class="col-sm-8 main-section">
                <div class="modal-content">
                <p>All objects Information</p>
                <input type="submit" value="Continue">

                <p>View transactions</p>
                <input type="submit" value="Continue">

                <p>Report a product</p>
                <input type="submit" value="Continue">

                <p>Add New Product</p>
                <input type="submit" value="Continue">

                <p>Edit product</p>
                <input type="submit" value="Continue">

                <p>Delete product</p>
                <input type="submit" value="Continue">
                </div>
            </div>
        </div>
    </body>
</html>